"""autobase

Revision ID: 9b820fdf86b2
Revises: 257450ebddfb
Create Date: 2021-05-01 07:42:47.399565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b820fdf86b2'
down_revision = '257450ebddfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autobase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.String(length=64), nullable=True),
    sa.Column('consumer_key', sa.String(length=64), nullable=True),
    sa.Column('consumer_secret', sa.String(length=64), nullable=True),
    sa.Column('access_key', sa.String(length=64), nullable=True),
    sa.Column('access_secret', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autobase_screen_name'), 'autobase', ['screen_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autobase_screen_name'), table_name='autobase')
    op.drop_table('autobase')
    # ### end Alembic commands ###
