"""timestamp

Revision ID: cd3feb7cac4e
Revises: 9b820fdf86b2
Create Date: 2021-05-01 07:49:37.660173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3feb7cac4e'
down_revision = '9b820fdf86b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autobase', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autobase', 'timestamp')
    # ### end Alembic commands ###
